"""Stub file for custom_components/reflex_charts/chart.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
import reflex as rx
from reflex.vars import Var
from .base import ChartJSBase

class ChartCanvas(ChartJSBase):
    @classmethod
    def create(
        cls,
        *children,
        type: Var[str] | str | None = None,
        data: Var[dict] | dict | None = None,
        options: Var[dict] | dict | None = None,
        plugins: Var[list] | list | None = None,
        width: Var[int] | int | None = None,
        height: Var[int] | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[Any]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ChartCanvas":
        """Create the component.

        Args:
            *children: The children of the component.
            type: The chart controller to use: one of reflex_charts.constants.CHART_TYPES.
            data: Chart.js ``data`` object: ``{"labels": [...], "datasets": [...]}``.
            options: Chart.js ``options`` object (scales, plugins, animations, ...).
            plugins: Per-chart inline plugins (advanced; usually configured via options).
            width: Fallback width/height in pixels when the parent does not constrain size.
            height: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Native canvas click. The Chart.js onClick receives ``(event, activeElements, chart)``; we surface the active elements so a Reflex state handler can react to clicked datapoints.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""
        ...

def chart(type: str = "line", **props) -> rx.Component: ...
def line(**props) -> rx.Component: ...
def bar(**props) -> rx.Component: ...
def radar(**props) -> rx.Component: ...
def doughnut(**props) -> rx.Component: ...
def pie(**props) -> rx.Component: ...
def polar_area(**props) -> rx.Component: ...
def bubble(**props) -> rx.Component: ...
def scatter(**props) -> rx.Component: ...
